
CFLAGS = -Wall -g

# Portul pe care asculta serverul (de completat)
PORT = 

# Adresa IP a serverului (de completat)
IP_SERVER = 

# ID subscriber (de completat)
ID_SUBSCRIBER = 

all: server subscriber

# Compileaza server.c
server: server.c

# Compileaza subscriber.c
subscriber: subscriber.c

.PHONY: clean run_server run_subscriber

# Ruleaza serverul
run_server:
	./server ${PORT}

# Ruleaza clientul
run_subscriber:
	./client ${ID_SUBSCRIBER} ${IP_SERVER} ${PORT_SERVER}

clean:
	rm -f server subscriber
